DROP TABLE TRECHOS;

DROP SEQUENCE SEQ_AEROPORTOS;
DROP TABLE AEROPORTOS;

DROP SEQUENCE SEQ_AERONAVES;
DROP TABLE AERONAVES;

CREATE SEQUENCE AERONAVES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AEROPORTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VOOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TRECHOS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE AEROPORTOS(
    CODIGO INTEGER DEFAULT AEROPORTOS_SEQ.NEXTVAL NOT NULL PRIMARY KEY, 
    NOME VARCHAR2(500) NOT NULL,
    SIGLA VARCHAR2(10) NOT NULL,
    CIDADE VARCHAR2(200) NOT NULL,
    PAIS VARCHAR2(100) NOT NULL,
    CONSTRAINT UN_SIGLA UNIQUE(SIGLA)
);

CREATE TABLE AERONAVES(
    CODIGO INTEGER DEFAULT AERONAVES_SEQ.NEXTVAL NOT NULL PRIMARY KEY,
    FABRICANTE VARCHAR2(100) NOT NULL,
    MODELO VARCHAR2(100) NOT NULL,
    ANO_FABRICACAO INTEGER NOT NULL,
    TOTAL_ASSENTOS INTEGER NOT NULL,
    REFERENCIA VARCHAR2(10) NOT NULL,
    
    CONSTRAINT CK_FABRICANTE_VALIDO CHECK 
        (FABRICANTE IN ('Airbus', 'Boeing', 'Embraer')),
        
    CONSTRAINT CK_ANO_VALIDO CHECK 
        (ANO_FABRICACAO BETWEEN 1990 AND 2023),

    CONSTRAINT CK_TOTAL_ASSENTOS CHECK
        (TOTAL_ASSENTOS BETWEEN 100 AND 1000),
    
    CONSTRAINT UN_REFERENCIA UNIQUE (REFERENCIA)
);

CREATE TABLE VOOS(
    CODIGO INTEGER DEFAULT VOOS_SEQ.NEXTVAL NOT NULL PRIMARY KEY,
    AERONAVE INTEGER NOT NULL,
    AEROPORTO_SAIDA INTEGER NOT NULL,
    AEROPORTO_DESTINO INTEGER NOT NULL,
    ESCALAS INTEGER,
    VALOR_PASSAGEM INTEGER NOT NULL,
    DATA_SAIDA VARCHAR2(20),
    HORA_SAIDA VARCHAR2(20),
    DATA_CHEGADA VARCHAR2(20),
    HORA_CHEGADA VARCHAR2(20),

    CONSTRAINT FK_ORIGEM_AEROPORTO FOREIGN KEY (AEROPORTO_SAIDA) 
    REFERENCES AEROPORTOS(CODIGO),
    
    CONSTRAINT FK_DESTINO_AEROPORTO FOREIGN KEY (AEROPORTO_DESTINO)
    REFERENCES AEROPORTOS(CODIGO),
    
    CONSTRAINT FK_AERONAVE FOREIGN KEY(AERONAVE)
    REFERENCES AERONAVES(CODIGO)
);

CREATE TABLE TRECHOS(
    CODIGO INTEGER DEFAULT TRECHOS_SEQ.NEXTVAL NOT NULL PRIMARY KEY,
    NOME VARCHAR2(200) NOT NULL,
    ORIGEM INTEGER NOT NULL,
    DESTINO INTEGER NOT NULL,
    AERONAVE INTEGER NOT NULL,
    
    CONSTRAINT CK_ORIGEM_DESTINO_DIFERENTES CHECK (ORIGEM != DESTINO)
);

-- INSERINDO ALGUNS AEROPORTOS

INSERT INTO AEROPORTOS 
(CODIGO, NOME, SIGLA, CIDADE, PAIS)
VALUES
(AEROPORTOS_SEQ.NEXTVAL, 'Viracopos', 'VCP', 'Campinas', 'Brasil');

INSERT INTO AEROPORTOS 
(CODIGO, NOME, SIGLA, CIDADE, PAIS)
VALUES
(AEROPORTOS_SEQ.NEXTVAL, 'Garulhos', 'GRU', 'Guarulhos', 'Brasil');

INSERT INTO AEROPORTOS 
(CODIGO, NOME, SIGLA, CIDADE, PAIS)
VALUES
(AEROPORTOS_SEQ.NEXTVAL, 'Fort Lauderdale-Hollywood', 'FLL', 
'Fort Lauderdale', 'Estados Unidos');

INSERT INTO AEROPORTOS 
(CODIGO, NOME, SIGLA, CIDADE, PAIS)
VALUES
(AEROPORTOS_SEQ.NEXTVAL, 'Charles de Gaulle', 'CDG', 
'Paris', 'França');

INSERT INTO AEROPORTOS 
(CODIGO, NOME, SIGLA, CIDADE, PAIS)
VALUES
(AEROPORTOS_SEQ.NEXTVAL, 'Flughafen Zürich', 'ZRH', 
'Zürich', 'Suiça');

-- INSERINDO ALGUMAS AERONAVES

INSERT INTO AERONAVES
(CODIGO, FABRICANTE, MODELO, ANO_FABRICACAO, 
TOTAL_ASSENTOS, REFERENCIA) VALUES 
(AERONAVES_SEQ.NEXTVAL, 'Boeing', '797', 2000, 360, 'AB-1234');

INSERT INTO AERONAVES
(CODIGO, FABRICANTE, MODELO, ANO_FABRICACAO, 
TOTAL_ASSENTOS, REFERENCIA) VALUES 
(AERONAVES_SEQ.NEXTVAL, 'Airbus', 'A380', 2020, 900, 'AB-8974');

INSERT INTO AERONAVES
(CODIGO, FABRICANTE, MODELO, ANO_FABRICACAO, 
TOTAL_ASSENTOS, REFERENCIA) VALUES 
(AERONAVES_SEQ.NEXTVAL, 'Airbus', 'A320', 2022, 320, 'XP-4421');

INSERT INTO AERONAVES
(CODIGO, FABRICANTE, MODELO, ANO_FABRICACAO, 
TOTAL_ASSENTOS, REFERENCIA) VALUES 
(AERONAVES_SEQ.NEXTVAL, 'Embraer', 'E195-E2', 2022, 144, 'EM-9832');

-- INSERINDO ALGUNS TRECHOS

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Campinas(vcp) - Fort Lauderdale(FLL)', 1, 3, 4);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Fort Lauderdale(FLL) - Campinas(vcp)', 3, 1, 4);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Campinas(vcp) - Fort Lauderdale(FLL)', 1, 3, 3);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE) 
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Fort Lauderdale(FLL) - Campinas(vcp)', 3, 1, 3);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Guarulhos(GRU) - Campinas(VCP)', 2, 1, 3);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Campinas(VCP) - Guarulhos(GRU)', 1, 2, 3);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Guarulhos(GRU) - Campinas(VCP)', 2, 1, 3);

INSERT INTO TRECHOS
(CODIGO, NOME, ORIGEM, DESTINO, AERONAVE)
VALUES
(TRECHOS_SEQ.NEXTVAL, 'Campinas(VCP) - Guarulhos(GRU)', 1, 2, 3);

COMMIT;

select * from aeronaves;
select * from aeroportos;
select * from trechos;
select * from voos;

SELECT
  V.CODIGO AS Codigo_Voo,
  V.ESCALAS,
  SAIDA.NOME AS Aeroporto_Saida,
  V.HORA_SAIDA,
  V.DATA_SAIDA,
  DESTINO.NOME AS Aeroporto_Destino,
  V.HORA_CHEGADA,
  V.DATA_CHEGADA,
  V.VALOR_PASSAGEM
FROM
  VOOS V
JOIN
  AEROPORTOS SAIDA ON V.AEROPORTO_SAIDA = SAIDA.CODIGO
JOIN
  AEROPORTOS DESTINO ON V.AEROPORTO_DESTINO = DESTINO.CODIGO
WHERE
  DESTINO.CIDADE = 'Fort Lauderdale'
  AND V.DATA_SAIDA = '2023-11-22';